---
- name: working with file module
  hosts: all
  tasks:
    - name: creating dvsbatch1.txt file in servers
      file:
        path: /tmp/dvsbatch1.txt
        owner: ec2-user
        group: ec2-user
        mode: '0644'
        state: touch
