---
- name: installing dependencies
  command: amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2

- name: installing apache
  yum:
    name: httpd
    state: present

- name: enable apache
  systemd:
    name: httpd
    enabled: yes

- name: downlaoding wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    force: yes

- name: Alligning the configuration
  shell: |
    cd /tmp
    tar -xzf wordpress.tar.gz
    cp -r wordpress/* /var/www/html/

- name: copying wp-configure.php
  template:
    src: wp-config.php
    dest: /var/www/html/
  notify: apache restart

- name: Setting the permissions
  file: path=/var/www state=directory recurse=yes owner=apache group=apache mode="0755"
  notify: apache restart
