---
- name: Installing mysql server
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - MySQL-python
    - mariadb-server

- name: enabling mysql software
  systemd:
    name: mariadb
    enabled: yes

- name: restart mariadb service
  systemd:
    name: mariadb
    state: restarted

- name: Creating the User admin
  mysql_user:
    name: "{{db_user}}"
    password: "{{db_password}}"
    priv: '*.*:ALL'
    state: present
    host: '%'

- name: Creating the database 
  mysql_db:
    name: "{{db_name}}"
    state: present
